site:
  name: "RexZ Docs | Ultimate AntiNuke & Security Bot for Discord"
  description: "Explore the official documentation for RexZ, the advanced Anti-Nuke, Security, and Moderation bot for Discord. Protect your server from raids, automate moderation, and enhance security."
  keywords: "rexz, antinuke, security, discordbot, discord"
  author: "BxBY"
  base: "/"
  permalink: "/:slug/"
  sitemap: true
  googleAnalytics: "G-V55PGEYHBX"
  html:
    head: |
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-V55PGEYHBX"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-V55PGEYHBX');
      </script>
    footer: |
      <script>
        console.log("Custom footer script loaded!");
      </script>

  # Open Graph (OG) for social media preview
  openGraph:
    title: "RexZ Docs | Ultimate AntiNuke & Security Bot for Discord"
    description: "Explore the official documentation for RexZ, the advanced Anti-Nuke, Security, and Moderation bot for Discord. Protect your server from raids, automate moderation, and enhance security."
    image: "/img/favicon.png"
    type: "website"

# Navigation settings (Optional)
navigation:
  - title: Home
    link: /index.md
  - title: Privacy Policy
    link: /privacypolicy.md
  - title: Setup
    link: /setup.md
